santio/fix/multi connection pool
IngotGG/iron pull request #20
Opened 2024-09-24 03:53 UTC by SantioMC

- **feat: initial controller commit**
- **feat: continued controllers work**
- **feat: cache controllers**
- **feat: expose iron to allow extensions**
- **feat: create readme for controllers**
- **fix: reserved keywords**
- **feat: Clean up a bit of work**
- **feat: attempt fix nullable insertion**
- **fix: better errors for modeling data**
- **fix: default constructor marker**
- **feat: controller upserting**
- **fix: jvm overloads on iron constructor**
- **feat: java support (wip)**
- **fix: java support**
- **feat: support optionals**
- **fix: single coroutine scope**
- **feat: deferred executor**
- **fix: language annotation**
- **misc: update docs**
- **fix: multi connection pool**

2024-09-27 07:01 UTC, DebitCardz requested changes

2024-09-27 07:01 UTC, DebitCardz commented on src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
> +    private fun push(connection: Connection) {
docs

2024-09-27 07:01 UTC, DebitCardz commented on src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
> +    private fun pull(): Connection? {
docs

2024-09-27 07:01 UTC, DebitCardz commented on src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
> +        openConnections.decrementAndGet()
can we set a variable of the output of `AtomicInteger#decrementAndGet` and use that for the log instead?

2024-09-27 07:01 UTC, DebitCardz commented on src/main/kotlin/gg/ingot/iron/pool/MultiConnectionPool.kt
> +        logger.trace("Acquired a connection from the pool, open connections: {}", openConnections.get())
can we also set this to a variable for logging? just for consistency.

2024-10-12 18:01 UTC, SantioMC commented
Closing in favor of #21

2024-10-12 18:01 UTC, closed without merging